name: Compile GCC aarch64-zyc-linux-gnu

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
  
    container: 
      image: zycromerz/kerneldocker:v2

    steps:
    - uses: actions/checkout@v2
    - name: Compile GCC
      env:
        GIT_SECRET: ${{ secrets.GIT_SECRET }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: |
        chmod +x do-now.sh
        . ./do-now.sh